### ISSUE TITLE
Simplified implementation

### ISSUE THREAD

**Issue by fbergroth** [emacsorphanage/evil-anzu#2]
Hi, thanks for creating this.

I noticed some problems and found a simpler implementation to support anzu in evil.

The whole package can be replaced with:

``` el
(defadvice evil-search (after evil-anzu-compat (string forward &optional regexp-p start) activate)
  (anzu--cons-mode-line-search)
  (let ((isearch-regexp regexp-p))
    (anzu--update string)))

(defadvice evil-flash-hook (after evil-anzu-compat activate)
  ;; Prevent flickering, only run if timer is not active
  (unless (memq evil-flash-timer timer-list)
    (anzu--reset-mode-line)))
```
- Prevents flickering

The old version flickered both the search results and the mode line when pressing n or N.
- Supports all search commands

In particular, the following commands did not work before:

```
*    evil-search-word-forward
#    evil-search-word-backward
g *  evil-search-unbounded-word-forward
g #  evil-search-unbounded-word-backward
```

Maybe this is simple enough to be put directly in an `anzu-setup-evil` function inside `anzu.el`? I can make this into a pull request if you want, either to `emacs-evil-anzu` or to `emacs-anzu`.

Cheers! :)

**Comment by fbergroth** [comment]
@syl20bnr looks like you also tried to integrate anzu with evil in spacemacs. Could you try this out? I might have missed some corner case.

**Comment by oscarfv** [comment]
I just started using it and so far it works fine. I'll report back any problems in case some arises.

**Comment by syohex** [comment]
@fbergroth Thanks. Could you make a pull request of this ?

**Comment by syl20bnr** [comment]
Ideally I will replace the `anzu` integration with evil in spacemacs with `evil-anzu`.

**Comment by syl20bnr** [comment]
@fbergroth Slick and efficient, it is now part of spacemacs: https://github.com/syl20bnr/spacemacs/commit/8baee10855fc44e3e349129f7a4a9565b1f5abea
@syohex thank you for the evil integration package
