### ISSUE TITLE
Counter doesn't reappear when hitting `n` or `N`

### ISSUE THREAD

**Issue by max-baz** [emacsorphanage/evil-anzu#4]
@fbergroth, I'm extracting our discussion at #1 into a separate issue.

The workflow I'm testing is the same as there, but failure happens on the step 3.
1. Hit `/` and type some text -> number of matches is visible (OK)
   ![image](https://cloud.githubusercontent.com/assets/1177900/5683601/80652ca0-9829-11e4-832b-380229c3c498.png)
2. Hit `Enter` -> cursor moved to the first match, number of matches is not visible (OK)
   ![image](https://cloud.githubusercontent.com/assets/1177900/5683649/e1f87b2a-9829-11e4-9c4c-e607cd9c3f76.png)
3. Hit `n` -> cursor moved to the next match, number of matches is not visible (NOT OK)

I expect the counter to reappear when I hit `n` or `N`.

I assume the comment @syohex made in #1 about remapping `n` and `N` is no longer applicable, right?

I'm on Emacs 24.4.1 64bit for Windows.
I can do more testing on Linux in the evening.

**Comment by fbergroth** [comment]
Do you still have `n` and `N` bound to `evil-anzu-search-next` and `evil-anzu-search-previous`? Those functions have been removed, no custom mappings should be necessary. `evil-search-next` should work out of the box.

**Comment by max-baz** [comment]
I removed these mappings:

> I assume the comment @syohex made in #1 about remapping n and N is no longer applicable, right?

My entire config now is simply `(global-anzu-mode t)`.

So you are saying that you cannot reproduce these steps? Then I'll test more later today, and come back with the results.

**Comment by fbergroth** [comment]
Unfortunately I cannot reproduce it. The minimal configuration should just be

``` el
;; make sure you explicitly require 'evil-anzu and not just 'anzu
;; this is really all that is necessary for evil mode
(require 'evil-anzu) 

;; to enable anzu for isearch
(global-anzu-mode)
```

I tested this with a blank emacs configuration. Also make sure you restarted emacs after upgrading, in case some old advices are to blame.

**Comment by syohex** [comment]
@z0rch Sorry I did not tell you about #2 changes.

**Comment by fbergroth** [comment]
@z0rch it really seems that you have `(require 'anzu)` instead of `(require 'evil-anzu)`. I get the same behavior that way.

**Comment by max-baz** [comment]
@fbergroth, that is exactly what happens!

Apparently, this is a bug (or my misunderstanding) of the `el-get` package manager. The documentation states, that it will require "the recipe name" (which in my case is "evil-anzu"), but it is requiring "anzu".

I'll contact `el-get` to verify whether this is a bug or not.

For people like me, until the recipe for "evil-anzu" appears in "el-get" repository, this one works fine for me:

``` elisp
(setq el-get-sources (append el-get-sources '(
  (:name evil-anzu
   :type github
   :pkgname "syohex/emacs-evil-anzu"
   :depends (evil anzu)
   :features (evil-anzu)   ;; ---- this is the "fix"
   :after (progn
      (global-anzu-mode t)
)))))
```

Thank you guys for the support!
